### ISSUE TITLE
Missing header file

### ISSUE THREAD

**Issue by Eidonko** [raboof/sfarkxtc#12]
$ make
g++   -L/usr/local/lib  sfarkxtc.cpp  -lsfark -lz -o sfarkxtc
sfarkxtc.cpp:37:10: fatal error: sfArkLib.h: No such file or directory
 #include <sfArkLib.h>
          ^~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: sfarkxtc] Error 1

**Comment by zvezdochiot** [comment]
See README:

https://github.com/raboof/sfArkLib

**Comment by raboof** [comment]
indeed sfArkXtc requires sfArkLib to be installed first. Feel free to reopen when this needs further details.
