### ISSUE TITLE
Compiling question concerning sfArkLib.h

### ISSUE THREAD

**Issue by QuaxEros** [raboof/sfarkxtc#4]
Hallo raboof,

Tried to "make" after putting sfArkLib.h (from sfArkLib) in the same directory. Still fails with "file not found" error.
 I should say i almost never "built" or worked with git before. Should this work or do i really need to install sfArkLib before or is the location of sfArkLib.h not correct? (you say in the readme "If you just want to convert an sfArk file to sf2, check out https://github.com/raboof/sfArkXTm" but then mention sfArkLib again as a prerequisite.)
Dank voor your work!

(edit) ...Ahum...shame on me. Looked good at my system and figured out where my header files live and the function of -dev packages and such :) . Will read some more before asking dumb questions.
Compiled sfArkLib (with just an "unused value" warning) and sfArkxtc without problem. Thanx

**Comment by raboof** [comment]
I tried to improve the documentation a bit! Thanks for getting in touch :)
