### ISSUE TITLE
Compile on Mac

### ISSUE THREAD

**Issue by kakyoism** [raboof/sfarkxtc#6]
On Mac OS X 10.10, I had to add "-L/usr/local/lib" to "LDLIBS" flag to make it compile.
This is because the sfArkLib's "make install" copies things over there, which is not part of the default dynamic library path.

If you have time, you might want to add this to your make file.
Thanks.

**Comment by raboof** [comment]
Looks like that should go into the LDFLAGS (https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html) - but I'm surprised /usr/local/lib isn't on the default path under MacOS X. Perhaps we should be writing it somewhere else on MacOSX, too?

What compiler are you using?

**Comment by kakyoism** [comment]
My compiler:
$ clang -v
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
